"""relate user to book

Revision ID: ab4aa19befb7
Revises: 465c605a20ff
Create Date: 2024-11-08 09:32:52.581558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ab4aa19befb7'
down_revision: Union[str, None] = '465c605a20ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Books', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'Books', 'Users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Books', type_='foreignkey')
    op.drop_column('Books', 'user_id')
    # ### end Alembic commands ###
